language: python
python:
    - 2.6
    - 2.7.12

    
install:
  - pip install --upgrade pip
  - pip install requests
  - pip install gunicorn

services:
  - mysql

script:
  - sudo apt-get install mysql-server
  - pytest test
  - gunicorn main:app --bind 0.0.0.0:8000
