language: python
python:
    - 2.6
    - 2.7.12

    
install:
  - pip install --upgrade pip
  - pip install requests
  - pip install gunicorn
  - pip install MySQL-python
  - pip install falcon

services:
  - mysql

script:
  - sudo apt-get install mysql-server
  - sudo apt-get install libmysqlclient-dev
  - gunicorn main:app --bind 0.0.0.0:8000
  - pytest test
