language: python
python:
    - 2.6
    - 2.7.12

    
install:
  - pip install --upgrade pip
  - pip install requests
  - pip install gevent
  - pip install gunicorn
  - pip install MySQL-python
  - pip install falcon

services:
  - mysql

before_script:
- mysql -u root -e 'CREATE DATABASE processodesoftware;'
- mysql -u root -e "CREATE USER 'pds'@'localhost' IDENTIFIED BY 'pds';"
- mysql -u root -e "GRANT ALL ON processodesoftware.* TO 'pds'@'localhost';"
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('123456') WHERE user='pds';\nFLUSH PRIVILEGES;\n" | mysql -u root
- mysql -u root processodesoftware < bd.sql

script:
  - sudo apt-get install mysql-server
  - sudo apt-get install libmysqlclient-dev
  - gunicorn main:app --bind 0.0.0.0:8000 &
  - pytest test

notifications:
  slack: processosdesoftware:4Zi0F7Ktu2A4Id3xBlz4M8Wx
