language: python
python:
    - 2.6
    - 2.7.12

    
install:
  - pip install --upgrade pip
  - pip install requests


services:
  - mysql

script:
  - sudo apt-get install mysql-server
  - pytest test
